# Generated by Django 4.0.4 on 2022-05-08 15:25

from django.db import migrations

def create_data(apps, schema_editor):
    MunicipalPortal = apps.get_model('customers', 'MunicipalPortal')
    MunicipalPortal(name="Portal da Transparência de Aracaju", link="https://transparencia.aracaju.se.gov.br/").save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
